name: Firebase Deploy

on:
  push:
    tags:
    - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm install
    - name: Verify
      run: npm run lint && npm run stylelint
    - name: Add Keys
      run: 
    - name: Build
      run: npm run build
    - name: Deploy Hosting
      run: npx --package firebase-tools firebase deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }}
    - name: Deploy Firestore Rules
      run: npx --package firebase-tools firebase deploy --only firestore:rules --token ${{ secrets.FIREBASE_TOKEN }}
    - name: Install function dependencies
      run: cd functions && npm install
    - name: Deploy Functions
      run: npx --package firebase-tools firebase deploy --only functions --token ${{ secrets.FIREBASE_TOKEN }}
