name: Pull Request Verify

on: [push]

jobs:
  verify:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install yarn
      run: npm i g yarn
    - name: Install dependencies
      run: yarn install
    - name: Verify ESLint
      run: yarn lint
    - name: Verify StyleLint
      run: yarn stylelint
    - name: Build
      run: yarn build
